import type { Metadata } from "next";
import './styles/globals.css';
import AosInit from './components/AosInit';


export const metadata: Metadata = {
  title: "Mélanie Bruzac - Développeuse Front-end",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      
      <body>
        <AosInit />
        {children}
      </body>
    
    </html>
  );
}
